# https://forums.docker.com/t/docker-not-found-in-jenkins-pipeline/31683
version: '3.9'
services:
    jenkins-tutorial:
        build: .
        image: myjenkins-blueocean:private
        environment:
            - DOCKER_SOCKET=/var/run/docker.sock
            - DOCKER_GROUP=docker
            - JENKINS_USER=jenkins
        ports:
            - 8080:8080
            - 50000:50000
        volumes:
            - jenkins_home:/var/jenkins_home
            - /var/run/docker.sock:/var/run/docker.sock
volumes:
    jenkins_home: {}
