FROM jenkins/jenkins:lts-jdk11

USER root

ENV DOCKER_SOCKET=/var/run/docker.sock \
    DOCKER_GROUP=docker \
    JENKINS_USER=jenkins

# each one of RUN, COPY, ADD instructions creates an image layer
RUN apt-get update && apt-get install -y \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg2 \
        software-properties-common
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
RUN apt-key fingerprint 0EBFCD88
RUN add-apt-repository \
        "deb [arch=amd64] https://download.docker.com/linux/debian \
        $(lsb_release -cs) stable"
RUN apt-get update && apt-get install -y docker-ce-cli

# docker command in the container fails because of "permission denied"
# but this still doesn't work
RUN groupadd -for -g 0 docker && usermod -aG docker jenkins

# https://github.com/jenkinsci/docker/issues/196
# RUN if [ -S ${DOCKER_SOCKET} ]; \
#     then \
#         DOCKER_GID=$(stat -c '%g' ${DOCKER_SOCKET}); \
#         groupadd -for -g ${DOCKER_GID} ${DOCKER_GROUP}; \
#         usermod -aG ${DOCKER_GROUP} ${JENKINS_USER}; \
#     else \
#         echo "${DOCKER_SOCKET} does not exist."; \
#     fi

USER jenkins
RUN jenkins-plugin-cli --plugins "blueocean:1.24.7 docker-workflow:1.26"
